data_source:
  gb_ons_postcode_dir_url: "https://www.arcgis.com/sharing/rest/content/items/487a5ba62c8b4da08f01eb3c08e304f6/data" # Aug 2023 data
  gb_ons_postcode_dir_file_path: "Data/ONSPD_AUG_2023_UK.csv" # Aug 2023 data
  UK_ons_postcode_dir: "s3://asf-heat-pump-suitability/source_data/ONSPD_AUG_2023_UK.csv"
  EW_census_housing_characteristics: "s3://asf-heat-pump-suitability/source_data/2021census_Mar2023update_housing_characteristics_E_W.xlsx" # 2021 census, Mar 2023 update
  EW_census_tenure: "s3://asf-heat-pump-suitability/source_data/2021census_2023Mar_tenure_E_W.csv"
  EW_census_number_of_rooms: "s3://asf-heat-pump-suitability/source_data/2021census_Mar2023_number_of_rooms_E_W.csv"
  EW_cdrc_dwelling_age: "s3://asf-heat-pump-suitability/source_data/2015cdrc_dwelling_ages_E_W.csv"
  GB_ons_garden_space_access: "s3://asf-heat-pump-suitability/source_data/ONS_Apr2020_access_to_garden_space.xlsx"
  GB_osopen_uprn_latlon: "s3://asf-heat-pump-suitability/source_data/osopenuprn_202405_csv.zip"
usecols:
  epc:
    - COUNTRY
    - ADDRESS1
    - ADDRESS2
    - POSTCODE
    - CURRENT_ENERGY_EFFICIENCY
    - CURRENT_ENERGY_RATING
    - CURR_ENERGY_RATING_NUM
    - ENERGY_RATING_CAT
    - UPRN
    - TENURE
    - PROPERTY_TYPE
    - BUILT_FORM
    - CONSTRUCTION_AGE_BAND
    - CO2_EMISSIONS_CURRENT
    - NUMBER_HABITABLE_ROOMS
    - HEATING_SYSTEM
    - HEATING_FUEL
mapping:
  build_year_pre_cols:
    - BP_PRE_1900
    - BP_1900_1918
    - BP_1919_1929
  build_year_post_cols:
    - BP_1930_1939
    - BP_1945_1954
    - BP_1955_1964
    - BP_1965_1972
    - BP_1973_1982
    - BP_1983_1992
    - BP_1993_1999
    - BP_2000_2009
    - BP_2010_2015
  pre_post_1930_epc:
    "England and Wales: before 1900": "pre_1930"
    "Scotland: before 1919": "pre_1930"
    "1900-1929": "pre_1930"
    "1930-1949": "post_1930"
    "1950-1966": "post_1930"
    "1965-1975": "post_1930"
    "1976-1983": "post_1930"
    "1983-1991": "post_1930"
    "1991-1998": "post_1930"
    "1996-2002": "post_1930"
    "2003-2007": "post_1930"
    "2007 onwards": "post_1930"
    "unknown": "unknown"
    "UNKNOWN": "unknown"
