from collections import OrderedDict

import polars as pl

onspd_schema = OrderedDict(
    [
        ("pcd", pl.String),
        ("pcd2", pl.String),
        ("pcds", pl.String),
        ("dointr", pl.Int64),
        ("doterm", pl.String),
        ("oscty", pl.String),
        ("ced", pl.String),
        ("oslaua", pl.String),
        ("osward", pl.String),
        ("parish", pl.String),
        ("usertype", pl.Int64),
        ("oseast1m", pl.Int64),
        ("osnrth1m", pl.Int64),
        ("osgrdind", pl.Int64),
        ("oshlthau", pl.String),
        ("nhser", pl.String),
        ("ctry", pl.String),
        ("rgn", pl.String),
        ("streg", pl.Int64),
        ("pcon", pl.String),
        ("eer", pl.String),
        ("teclec", pl.String),
        ("ttwa", pl.String),
        ("pct", pl.String),
        ("itl", pl.String),
        ("statsward", pl.String),
        ("oa01", pl.String),
        ("casward", pl.String),
        ("npark", pl.String),
        ("lsoa01", pl.String),
        ("msoa01", pl.String),
        ("ur01ind", pl.String),
        ("oac01", pl.String),
        ("oa11", pl.String),
        ("lsoa11", pl.String),
        ("msoa11", pl.String),
        ("wz11", pl.String),
        ("sicbl", pl.String),
        ("bua11", pl.String),
        ("buasd11", pl.String),
        ("ru11ind", pl.String),
        ("oac11", pl.String),
        ("lat", pl.Float64),
        ("long", pl.Float64),
        ("lep1", pl.String),
        ("lep2", pl.String),
        ("pfa", pl.String),
        ("imd", pl.Int64),
        ("calncv", pl.String),
        ("icb", pl.String),
        ("oa21", pl.String),
        ("lsoa21", pl.String),
        ("msoa21", pl.String),
    ]
)
microsoft_datalinks = OrderedDict([("Location", str), ("QuadKey", str), ("Url", str), ("Size", str)])
nrs_dwellings = OrderedDict(
    [
        ("Data Zone code", pl.String),
        ("Data Zone name", pl.String),
        ("Council area code", pl.String),
        ("Council area name", pl.String),
        ("Total number of dwellings", pl.Int64),
        ("Occupied dwellings", pl.Int64),
        ("Vacant dwellings", pl.Int64),
        ("Unoccupied dwellings exempt from paying Council Tax", pl.Int64),
        ("Long-term empty dwellings \r\n[Note 6]", pl.Int64),
        ("Second homes", pl.Int64),
        ("Occupied dwellings exempt from paying Council Tax", pl.Int64),
        ("Dwellings with a 'single adult' Council Tax discount", pl.Int64),
        ("Occupied dwellings\r\n(%)", pl.Int64),
        ("Vacant dwellings\r\n(%)", pl.Int64),
        ("Unoccupied dwellings exempt from paying Council Tax\r\n(%)", pl.Int64),
        ("Empty dwellings \r\n(%) \r\n[Note 6]", pl.Int64),
        ("Second homes\r\n(%)", pl.Int64),
        ("Occupied dwellings exempt from paying Council Tax\r\n(%)", pl.Int64),
        ("Dwellings with a 'single adult' Council Tax discount\r\n(%)", pl.Int64),
    ]
)
