import polars as pl
from collections import OrderedDict


onspd_schema = OrderedDict(
    [
        ("pcd", pl.String),
        ("pcd2", pl.String),
        ("pcds", pl.String),
        ("dointr", pl.Int64),
        ("doterm", pl.String),
        ("oscty", pl.String),
        ("ced", pl.String),
        ("oslaua", pl.String),
        ("osward", pl.String),
        ("parish", pl.String),
        ("usertype", pl.Int64),
        ("oseast1m", pl.Int64),
        ("osnrth1m", pl.Int64),
        ("osgrdind", pl.Int64),
        ("oshlthau", pl.String),
        ("nhser", pl.String),
        ("ctry", pl.String),
        ("rgn", pl.String),
        ("streg", pl.Int64),
        ("pcon", pl.String),
        ("eer", pl.String),
        ("teclec", pl.String),
        ("ttwa", pl.String),
        ("pct", pl.String),
        ("itl", pl.String),
        ("statsward", pl.String),
        ("oa01", pl.String),
        ("casward", pl.String),
        ("npark", pl.String),
        ("lsoa01", pl.String),
        ("msoa01", pl.String),
        ("ur01ind", pl.String),
        ("oac01", pl.String),
        ("oa11", pl.String),
        ("lsoa11", pl.String),
        ("msoa11", pl.String),
        ("wz11", pl.String),
        ("sicbl", pl.String),
        ("bua11", pl.String),
        ("buasd11", pl.String),
        ("ru11ind", pl.String),
        ("oac11", pl.String),
        ("lat", pl.Float64),
        ("long", pl.Float64),
        ("lep1", pl.String),
        ("lep2", pl.String),
        ("pfa", pl.String),
        ("imd", pl.Int64),
        ("calncv", pl.String),
        ("icb", pl.String),
        ("oa21", pl.String),
        ("lsoa21", pl.String),
        ("msoa21", pl.String),
    ]
)
