name: Run tests
on:
  pull_request:
    branches: [dev]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up conda environment
        uses: mamba-org/setup-micromamba@v2
        with:
          environment-file: environment.yaml
          environment-name: asf_heat_pump_suitability
          cache-environment: true
          create-args: python=3.11
      - name: Install package and dev dependencies
        run: |
          pip install -r requirements.txt -r requirements_dev.txt
          pip install -e .
        shell: micromamba-shell {0}
      - name: Run tests
        run: pytest --cov=asf_heat_pump_suitability --cov-report=term-missing
        shell: micromamba-shell {0}
